// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZt-U5otH1Pwifbxju6puqerAAH123pI',
    appId: '1:200573018670:web:108ce5c9baaad1c878b5bf',
    messagingSenderId: '200573018670',
    projectId: 'project6aap',
    authDomain: 'project6aap.firebaseapp.com',
    storageBucket: 'project6aap.firebasestorage.app',
    measurementId: 'G-MLYWMZ2EHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmufwGmdaCrdxRNDR5EqVV1jmPUS0ol0',
    appId: '1:200573018670:android:7e5ea9cdbdf6a74b78b5bf',
    messagingSenderId: '200573018670',
    projectId: 'project6aap',
    storageBucket: 'project6aap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyH4oPm5MiudBDrs2d84JiQuMnV18KPzU',
    appId: '1:200573018670:ios:057b15f64495602778b5bf',
    messagingSenderId: '200573018670',
    projectId: 'project6aap',
    storageBucket: 'project6aap.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyH4oPm5MiudBDrs2d84JiQuMnV18KPzU',
    appId: '1:200573018670:ios:057b15f64495602778b5bf',
    messagingSenderId: '200573018670',
    projectId: 'project6aap',
    storageBucket: 'project6aap.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxZt-U5otH1Pwifbxju6puqerAAH123pI',
    appId: '1:200573018670:web:2e609c4bc1f3cd4278b5bf',
    messagingSenderId: '200573018670',
    projectId: 'project6aap',
    authDomain: 'project6aap.firebaseapp.com',
    storageBucket: 'project6aap.firebasestorage.app',
    measurementId: 'G-9QH4JB0F9L',
  );
}
